version: "3.6"
services:

   mongodb:
     image: mongo
     ports:
       - 27017:27017

  twitter_api:
    image: alexburlacu/rtp-server:faf18x
    ports:
      - 4000:4000

  rtp:
    build:
      context: .
    ports:
      - 6666:6666